"""Regenerate every schema document in the repo.

    python tools/generate_schemas.py

What it writes:

* ``adapters/<name>/SCHEMA.md`` -- one contract per adapter, input and output
  in one file. Authored prose, generated field tables.
* ``schemas/*.schema.json`` -- the machine-readable form of the core's two
  contracts, for consumers who validate rather than read.

What it does **not** write is ``schemas/SCHEMA.md``, the core's contract. That
one is authored by hand, because annotated JSON with a worked example off a real
run says more than any generated field table, and no generator writes prose that
good. It is guarded a different way: ``tests/core/test_contracts.py`` fails when
a model field is missing from it, so the doc cannot silently fall behind the
code even though a human writes it.

That test also fails if any committed copy here is stale, so a field added
without a description does not reach a consumer quietly.
"""

from __future__ import annotations

import json
from pathlib import Path

from schema_docs import model_markdown

from adapters.valuation.program import Emission, ProgramFrame
from adapters.webui.payload import WebPayload
from hyp_gen.graph import KnowledgeGraph
from hyp_gen.hypothesis import SCHEMA_VERSION, HypothesisDocument

# The core's contract is one authored file -- see the module docstring.
CORE_SCHEMA = "schemas/SCHEMA.md"

ROOT = Path(__file__).resolve().parents[1]
ADAPTERS = ROOT / "adapters"
SCHEMAS = ROOT / "schemas"

GENERATED = "<!-- generated by tools/generate_schemas.py — edit the prose above, not the tables -->"

# --------------------------------------------------------------------------
# The core: one graph in, one hypothesis out.
# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# Adapters. Their input is always the core's output.
# --------------------------------------------------------------------------

ADAPTER_INPUT = """## Input — one or more `hypothesis.json`

{lede}

The input contract is the core's output contract, unchanged:
[`schemas/SCHEMA.md`](../../schemas/SCHEMA.md).

This adapter accepts **one or more** documents. The core emits one per run, so
several means several runs; each document carries its own provenance, and
`adapters.common.load()` refuses to bundle documents from different graphs —
their scores are not comparable and a shared header would claim they are.

{extra}
What this adapter may not do, like every adapter: read the knowledge graph,
call a model, or state anything the documents do not carry.
"""


def adapter_input(lede: str, extra: str = "") -> str:
    return ADAPTER_INPUT.format(lede=lede, extra=f"{extra}\n" if extra else "")


REPORT_OUTPUT = f"""## Output — markdown

Markdown text, written to one file per mode. Not a data format: the audience is
a person, and the only contract is what must never be dropped.

| Mode | File | Answers |
|---|---|---|
| `prose` (default) | `report.md` | What is this idea, is it any good, what would kill it, what next |
| `table` | `report-table.md` | Which of these should I look at first |
| `trace` | `report-trace.md` | Where did this come from |
| `full` | `report-full.md` | Is the work correct |

## What every mode must carry

A mode changes the form, never the safety. These survive all four:

- **failure badges** — `BLOCKED`, `CITATION REJECTED`, `INVALID`
- **halted verifications** — naming the gate that stopped it, so five passes
  and a halt never reads as six passes
- **error-level validation issues**
- **the absence-of-evidence notice** when coverage is thin

In `table` the flagged rows are restated at full width beneath the table,
because a flag inside a cell is easy to skim past.

## Two rules that keep `prose` short

- Argued fields — the falsifier, the decisive experiment, the strongest
  objection — are clipped to whole sentences and the clip is always marked `…`,
  because an argument that ends mid-case must not look like one that ended.
- The statement itself is never clipped. It is the hypothesis, and a hedged
  claim cut short reads as a flat one.

{GENERATED}
"""

WEBUI_OUTPUT = f"""## Output — cards JSON and an SVG

Two artifacts from the same input.

## `cards.json`

One card per hypothesis. The walk is rendered as a single string
(`pirfenidone --inhibits--> myofibroblast differentiation --contributes_to--> …`,
a reversed hop written `<--how--`), alongside the metrics that order the cards.

`highlights` are one-liners saying how the graph supports, contradicts or
qualifies the hypothesis. Every highlight is assembled from structured fields
and carries the ids it was built from in `refs`, so the UI can link each line
to its evidence — **no highlight states anything the document does not**.
Highlights are ordered weakest-first: failures, contradictions, cautions,
novelty, then support.

Rejection flags render on the card. The absence-of-evidence warning sits at
payload level, where no card-only view can drop it.

## `traces.svg`

A static SVG of the walks. No plotting dependency, it diffs, and it embeds in a
page unchanged.

Edges are coloured by what the evidence says. There is no "contradicted" flag
on a link — a link carries `yes`, `no` and `no_effect` finding lists — so
**red** means at least one finding argues against the edge (or reports no
effect), **blue** means every finding supports it, and **grey** means no
verbatim finding at all. Dashes are a second axis: dashed is `single_source`,
solid is more than one research group. The `✓ ✗ ∅` counts on each label say how
many findings sit on each side.

Nodes are deduplicated across traces, so two hypotheses crossing the same node
visibly converge, and rows are ordered by a barycentre pass so the edges do not
knot. The finely dotted grey edge is the hypothesis itself — the edge the graph
does *not* have.

{GENERATED}

"""

VALUATION_OUTPUT = f"""## Output — program briefs for the ROI model

One `*.program.json` per molecule, plus a record of what was skipped and why.

## Read this before reading a number

**Expect `NOT_DECISION_GRADE`.** A literature graph has no epidemiology, no
payer behaviour and no price of any basis. The brief goes over honestly empty,
the ROI model names every hole, and *that list is the answer* — present it as a
work order ("here are the inputs someone has to supply"), not as a failed run.

**Every rNPV in an unedited emission is `0.0`.** With no comparable prices there
is no price corridor, so the cash flow is zero by construction. Check
`decision_grade` before reading any summary, and never quote a percentile, a
ranking or a cash-at-risk figure off an ungraded result. A zero here means
nobody has supplied a price yet — it does not mean the idea is worthless.

**The valuation must not change the science.** A program screening badly does
not make its hypothesis weaker. Do not re-rank, re-word or drop a hypothesis
because of an ROI result; market size is not evidence. Report the two orderings
separately — where they disagree is usually the most interesting thing on the
page.

**Two hypotheses about one molecule are one program with two labels**, sharing
one patent clock. If the emission reports `labrador_two_label_limit`, say which
label was left out rather than presenting the program as covering all of them.

## The frame is the analyst's half

`emit` requires a `ProgramFrame` and its four year fields start `null`.
Currency, geography, route, launch year and above all the patent filing year
are analyst decisions, not graph findings — and a guessed filing year is
indistinguishable from a sourced one once it is in the JSON, while setting the
protected window, the one number this handoff can actually support.

{GENERATED}

"""


ADAPTER_HEADER = """# {title} adapter — Input ⇄ Output Contract

**This is the authoritative contract for this adapter.** The core's contract is
[`schemas/SCHEMA.md`](../../schemas/SCHEMA.md); this file says only what this
adapter adds on top of it.

"""


def documents() -> list[tuple[Path, str]]:
    """Every generated file, as (path, content).

    The core's SCHEMA.md is authored by hand and is deliberately absent here:
    annotated JSON with a worked example says more than a generated field table,
    and no generator writes prose that good. ``tests/core/test_contracts.py``
    guards it a different way -- by failing when a model field is missing from
    it.
    """
    return [
        (
            ADAPTERS / "report" / "SCHEMA.md",
            ADAPTER_HEADER.format(title="Report")
            + adapter_input(
                "The report adapter turns hypothesis documents into markdown "
                "somebody reads.",
                "`table` and `trace` mode are the ones that gain from several "
                "documents: one row each, and shared nodes drawn once.",
            )
            + "\n---\n\n"
            + REPORT_OUTPUT,
        ),
        (
            ADAPTERS / "webui" / "SCHEMA.md",
            ADAPTER_HEADER.format(title="Web UI")
            + adapter_input(
                "The webui adapter turns hypothesis documents into a card payload "
                "and an SVG of the graph walks."
            )
            + "\n---\n\n"
            + WEBUI_OUTPUT
            + model_markdown(WebPayload),
        ),
        (
            ADAPTERS / "valuation" / "SCHEMA.md",
            ADAPTER_HEADER.format(title="Valuation")
            + adapter_input(
                "The valuation adapter turns hypothesis documents into program "
                "briefs for the ROI model.",
                "It also requires a **`ProgramFrame`** -- the analyst's half of "
                "the input, which no graph can supply. Its fields are tabled "
                "below the output.",
            )
            + "\n---\n\n"
            + VALUATION_OUTPUT
            + model_markdown(Emission)
            + "\n"
            + model_markdown(ProgramFrame),
        ),
    ]


def json_schemas() -> list[tuple[Path, dict]]:
    graph = KnowledgeGraph.model_json_schema()
    graph["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    graph["$id"] = "https://labrador.dev/schemas/knowledge-graph.schema.json"
    graph["title"] = "KnowledgeGraph"
    graph["description"] = (
        "INPUT to hyp_gen. A literature knowledge graph. Prose contract: "
        + CORE_SCHEMA
    )

    hypothesis = HypothesisDocument.model_json_schema()
    hypothesis["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    hypothesis["$id"] = "https://labrador.dev/schemas/hypothesis.schema.json"
    hypothesis["title"] = "HypothesisDocument"
    hypothesis["description"] = (
        f"OUTPUT of hyp_gen, written as hypothesis.json (schema version "
        f"{SCHEMA_VERSION}). ONE hypothesis, with the provenance needed to judge "
        f"it. Prose contract: {CORE_SCHEMA}"
    )

    return [
        (SCHEMAS / "knowledge-graph.schema.json", graph),
        (SCHEMAS / "hypothesis.schema.json", hypothesis),
    ]


def write(path: Path, text: str) -> bool:
    """Write ``text`` to ``path``. Returns True when the file changed."""
    if path.exists() and path.read_text() == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return True


def main() -> int:
    changed = 0
    for path, text in documents():
        changed += write(path, text)
    for path, schema in json_schemas():
        changed += write(path, json.dumps(schema, indent=2, sort_keys=True) + "\n")
    total = len(documents()) + len(json_schemas())
    print(f"{changed} of {total} schema files updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
