"""Regenerate every schema document in the repo.

    python tools/generate_schemas.py

Two kinds of artifact, from one source of truth:

* ``INPUT_SCHEMA.md`` / ``OUTPUT_SCHEMA.md`` beside the code they describe --
  the core has a pair, and so does every adapter. Authored prose, generated
  field tables.
* ``schemas/*.schema.json`` -- the machine-readable form of the core's two
  contracts, for consumers who validate rather than read.

``tests/core/test_contracts.py`` fails if any committed copy is stale, so a
field added without a description, or a contract changed without a word about
why, does not reach a consumer quietly.
"""

from __future__ import annotations

import json
from pathlib import Path

from schema_docs import model_markdown

from adapters.valuation.program import Emission, ProgramFrame
from adapters.webui.payload import WebPayload
from hyp_gen.graph import KnowledgeGraph
from hyp_gen.hypothesis import SCHEMA_VERSION, HypothesisDocument

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "src" / "hyp_gen"
ADAPTERS = ROOT / "adapters"
SCHEMAS = ROOT / "schemas"

GENERATED = "<!-- generated by tools/generate_schemas.py — edit the prose above, not the tables -->"

# --------------------------------------------------------------------------
# The core: one graph in, one hypothesis out.
# --------------------------------------------------------------------------

CORE_INPUT = f"""# INPUT — the knowledge graph

`hyp_gen` reads exactly one JSON file: a literature knowledge graph. Everything
it can ever say comes from this file. If a fact is not here, it cannot appear
in a hypothesis, and that is the property that makes the output checkable.

A graph is: **things** (entities), **links** between them, **findings** that
back each link with a verbatim sentence, the **papers** those sentences came
from, **gaps** the builder flagged, and a **coverage** block saying how hard it
looked.

The three fields this app leans on hardest, and why:

- **`coverage`** — depth, how much of what was found was actually read, and
  whether the search truncated. Novelty that rests on "nobody has said this"
  is scaled by these numbers, and at `quick` depth the scaling factor is zero.
  Page one lies; a shallow search is not evidence of absence.
- **`findings`** — each carries a verbatim sentence, its paper, and whether it
  argues **for**, **against**, or for **no effect**. Support is recomputed from
  these rather than trusted from `links.confidence`, so a link asserting 0.9
  with one hedged preprint behind it will not score like one with two
  independent groups.
- **`links.where`** — the conditions a result was measured under. A link whose
  findings disagree is usually two experimental conditions rather than a
  conflict, which is why reconciling one is a first-class hypothesis here
  rather than a data-quality complaint.

Unknown fields are preserved rather than rejected: the graph builder owns this
schema and will grow it, and a new key upstream is not a reason for this app to
stop working.

Machine-readable form: [`schemas/knowledge-graph.schema.json`](../../schemas/knowledge-graph.schema.json).

{GENERATED}

"""

CORE_OUTPUT = f"""# OUTPUT — one hypothesis

A run writes exactly one file, `hypothesis.json`, holding **one hypothesis** —
the one that ranked first. Not a slate, not a list.

Many candidates are enumerated, scored, critiqued and ranked on the way there,
because that is how the winner is known. Only the winner crosses this boundary.
If nothing survives selection the run writes nothing and says so: an empty
answer with a clear next step is a real answer, and it is a better one than the
least bad candidate promoted to look like a finding.

Schema version **{SCHEMA_VERSION}**. Adding an optional field is a minor bump;
removing one, or narrowing what it may contain, is a major one.

## What makes the document self-contained

`provenance` travels with the claim because a hypothesis separated from what
produced it cannot be judged. Support 0.5 from a cautious run and support 0.5
from an ambitious one are not the same statement about the world, and the
number alone cannot tell them apart — so the stance, the coverage of the graph
it read, and how many candidates it beat all ship in the same file.

## Reading order for a consumer

1. `schema_version` — know what you are parsing.
2. `provenance.coverage` — how hard the graph was searched. Read this *before*
   the scores. Absence of evidence is not evidence of absence.
3. `hypothesis.verification.verdict` — one of `verified`, `qualified`,
   `unverified`, `rejected`. A verdict of `unverified` with `halted_at` set
   means gates below the halt **did not run**; they are not passes.
4. `hypothesis.issues` — anything at severity `error` means this is not
   presentable as a finding.
5. Only then, the claim itself.

## The rules the document promises

- Every id in `hypothesis.evidence` and in every claim's `cites` appears in the
  input graph. A citation outside what the model was shown is rejected before
  it can reach this file.
- `hypothesis.scores` is a vector, not a ranking. Support and novelty are
  separate axes on purpose: averaging them puts textbook statements first.
- `asks` names the exact request that would move this hypothesis, keyed by id,
  in the graph builder's own request shape. No prose to interpret.

Machine-readable form: [`schemas/hypothesis.schema.json`](../../schemas/hypothesis.schema.json).

{GENERATED}

"""

# --------------------------------------------------------------------------
# Adapters. Their input is always the core's output.
# --------------------------------------------------------------------------

ADAPTER_INPUT = """# INPUT — one or more `hypothesis.json`

{lede}

The input contract is the core's output contract, unchanged:
[`src/hyp_gen/OUTPUT_SCHEMA.md`](../../src/hyp_gen/OUTPUT_SCHEMA.md).

This adapter accepts **one or more** documents. The core emits one per run, so
several means several runs; each document carries its own provenance, and
`adapters.common.load()` refuses to bundle documents from different graphs —
their scores are not comparable and a shared header would claim they are.

{extra}
What this adapter may not do, like every adapter: read the knowledge graph,
call a model, or state anything the documents do not carry.
"""


def adapter_input(lede: str, extra: str = "") -> str:
    return ADAPTER_INPUT.format(lede=lede, extra=f"{extra}\n" if extra else "")


REPORT_OUTPUT = f"""# OUTPUT — markdown

Markdown text, written to one file per mode. Not a data format: the audience is
a person, and the only contract is what must never be dropped.

| Mode | File | Answers |
|---|---|---|
| `prose` (default) | `report.md` | What is this idea, is it any good, what would kill it, what next |
| `table` | `report-table.md` | Which of these should I look at first |
| `trace` | `report-trace.md` | Where did this come from |
| `full` | `report-full.md` | Is the work correct |

## What every mode must carry

A mode changes the form, never the safety. These survive all four:

- **failure badges** — `BLOCKED`, `CITATION REJECTED`, `INVALID`
- **halted verifications** — naming the gate that stopped it, so five passes
  and a halt never reads as six passes
- **error-level validation issues**
- **the absence-of-evidence notice** when coverage is thin

In `table` the flagged rows are restated at full width beneath the table,
because a flag inside a cell is easy to skim past.

## Two rules that keep `prose` short

- Argued fields — the falsifier, the decisive experiment, the strongest
  objection — are clipped to whole sentences and the clip is always marked `…`,
  because an argument that ends mid-case must not look like one that ended.
- The statement itself is never clipped. It is the hypothesis, and a hedged
  claim cut short reads as a flat one.

{GENERATED}
"""

WEBUI_OUTPUT = f"""# OUTPUT — cards JSON and an SVG

Two artifacts from the same input.

## `cards.json`

One card per hypothesis. The walk is rendered as a single string
(`pirfenidone --inhibits--> myofibroblast differentiation --contributes_to--> …`,
a reversed hop written `<--how--`), alongside the metrics that order the cards.

`highlights` are one-liners saying how the graph supports, contradicts or
qualifies the hypothesis. Every highlight is assembled from structured fields
and carries the ids it was built from in `refs`, so the UI can link each line
to its evidence — **no highlight states anything the document does not**.
Highlights are ordered weakest-first: failures, contradictions, cautions,
novelty, then support.

Rejection flags render on the card. The absence-of-evidence warning sits at
payload level, where no card-only view can drop it.

## `traces.svg`

A static SVG of the walks. No plotting dependency, it diffs, and it embeds in a
page unchanged.

Edges are coloured by what the evidence says. There is no "contradicted" flag
on a link — a link carries `yes`, `no` and `no_effect` finding lists — so
**red** means at least one finding argues against the edge (or reports no
effect), **blue** means every finding supports it, and **grey** means no
verbatim finding at all. Dashes are a second axis: dashed is `single_source`,
solid is more than one research group. The `✓ ✗ ∅` counts on each label say how
many findings sit on each side.

Nodes are deduplicated across traces, so two hypotheses crossing the same node
visibly converge, and rows are ordered by a barycentre pass so the edges do not
knot. The finely dotted grey edge is the hypothesis itself — the edge the graph
does *not* have.

{GENERATED}

"""

VALUATION_OUTPUT = f"""# OUTPUT — program briefs for the ROI model

One `*.program.json` per molecule, plus a record of what was skipped and why.

## Read this before reading a number

**Expect `NOT_DECISION_GRADE`.** A literature graph has no epidemiology, no
payer behaviour and no price of any basis. The brief goes over honestly empty,
the ROI model names every hole, and *that list is the answer* — present it as a
work order ("here are the inputs someone has to supply"), not as a failed run.

**Every rNPV in an unedited emission is `0.0`.** With no comparable prices there
is no price corridor, so the cash flow is zero by construction. Check
`decision_grade` before reading any summary, and never quote a percentile, a
ranking or a cash-at-risk figure off an ungraded result. A zero here means
nobody has supplied a price yet — it does not mean the idea is worthless.

**The valuation must not change the science.** A program screening badly does
not make its hypothesis weaker. Do not re-rank, re-word or drop a hypothesis
because of an ROI result; market size is not evidence. Report the two orderings
separately — where they disagree is usually the most interesting thing on the
page.

**Two hypotheses about one molecule are one program with two labels**, sharing
one patent clock. If the emission reports `labrador_two_label_limit`, say which
label was left out rather than presenting the program as covering all of them.

## The frame is the analyst's half

`emit` requires a `ProgramFrame` and its four year fields start `null`.
Currency, geography, route, launch year and above all the patent filing year
are analyst decisions, not graph findings — and a guessed filing year is
indistinguishable from a sourced one once it is in the JSON, while setting the
protected window, the one number this handoff can actually support.

{GENERATED}

"""


def documents() -> list[tuple[Path, str]]:
    """Every generated file, as (path, content)."""
    return [
        (CORE / "INPUT_SCHEMA.md", CORE_INPUT + model_markdown(KnowledgeGraph)),
        (CORE / "OUTPUT_SCHEMA.md", CORE_OUTPUT + model_markdown(HypothesisDocument)),
        (
            ADAPTERS / "report" / "INPUT_SCHEMA.md",
            adapter_input(
                "The report adapter turns hypothesis documents into markdown "
                "somebody reads.",
                "`table` and `trace` mode are the ones that gain from several "
                "documents: one row each, and shared nodes drawn once.",
            ),
        ),
        (ADAPTERS / "report" / "OUTPUT_SCHEMA.md", REPORT_OUTPUT),
        (
            ADAPTERS / "webui" / "INPUT_SCHEMA.md",
            adapter_input(
                "The webui adapter turns hypothesis documents into a card payload "
                "and an SVG of the graph walks."
            ),
        ),
        (
            ADAPTERS / "webui" / "OUTPUT_SCHEMA.md",
            WEBUI_OUTPUT + model_markdown(WebPayload),
        ),
        (
            ADAPTERS / "valuation" / "INPUT_SCHEMA.md",
            adapter_input(
                "The valuation adapter turns hypothesis documents into program "
                "briefs for the ROI model.",
                "It also requires a **`ProgramFrame`** — the analyst's half of "
                "the input, which no graph can supply. Its schema is in "
                "OUTPUT_SCHEMA.md beside this file.",
            ),
        ),
        (
            ADAPTERS / "valuation" / "OUTPUT_SCHEMA.md",
            VALUATION_OUTPUT + model_markdown(Emission) + "\n" + model_markdown(ProgramFrame),
        ),
    ]


def json_schemas() -> list[tuple[Path, dict]]:
    graph = KnowledgeGraph.model_json_schema()
    graph["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    graph["$id"] = "https://labrador.dev/schemas/knowledge-graph.schema.json"
    graph["title"] = "KnowledgeGraph"
    graph["description"] = (
        "INPUT to hyp_gen. A literature knowledge graph. Prose contract: "
        "src/hyp_gen/INPUT_SCHEMA.md"
    )

    hypothesis = HypothesisDocument.model_json_schema()
    hypothesis["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    hypothesis["$id"] = "https://labrador.dev/schemas/hypothesis.schema.json"
    hypothesis["title"] = "HypothesisDocument"
    hypothesis["description"] = (
        f"OUTPUT of hyp_gen, written as hypothesis.json (schema version "
        f"{SCHEMA_VERSION}). ONE hypothesis, with the provenance needed to judge "
        "it. Prose contract: src/hyp_gen/OUTPUT_SCHEMA.md"
    )

    return [
        (SCHEMAS / "knowledge-graph.schema.json", graph),
        (SCHEMAS / "hypothesis.schema.json", hypothesis),
    ]


def write(path: Path, text: str) -> bool:
    """Write ``text`` to ``path``. Returns True when the file changed."""
    if path.exists() and path.read_text() == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return True


def main() -> int:
    changed = 0
    for path, text in documents():
        changed += write(path, text)
    for path, schema in json_schemas():
        changed += write(path, json.dumps(schema, indent=2, sort_keys=True) + "\n")
    total = len(documents()) + len(json_schemas())
    print(f"{changed} of {total} schema files updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
